services:

  db:
    image: postgres:16.2

    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

    ports:
      - "5432:5432"

    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

    env_file:
      - .env


  app:
    container_name: app

    build: .

    ports:
      - '8000:8000'

    volumes:
      - .:/code

    depends_on:
      - db