"""update user model

Revision ID: 298eedb7e742
Revises: e5751ee80552
Create Date: 2024-06-11 18:14:38.737579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '298eedb7e742'
down_revision: Union[str, None] = 'e5751ee80552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__table', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False, server_default='example@mail.com'))
    op.add_column('user__table', sa.Column('password', sa.String(length=32), nullable=False, server_default='123'))
    op.alter_column('user__table', 'email', server_default='example@mail.com')
    op.alter_column('user__table', 'password', server_default='123')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__table', 'password')
    op.drop_column('user__table', 'email')
    # ### end Alembic commands ###
